# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoz', '0003_reviewpost_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='text',
            field=models.TextField(max_length=180),
        ),
    ]
