# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoz', '0005_requestpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
